PyTorch basics - Linear Regression from scratch

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
from subprocess import call

In [ ]:
import torch

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[0.4360, 0.1957, 1.0798],
        [0.0348, 1.2928, 0.5063]], requires_grad=True)
tensor([-0.2368,  0.0081], requires_grad=True)


In [ ]:
# Define the model
def model(x):
    return x @ w.t() + b
  
# Generate predictions
preds = model(inputs)
print(preds)
print(targets)

tensor([[ 91.1334, 110.9378],
        [125.7669, 149.3458],
        [126.5446, 205.6368],
        [ 92.6019,  77.8821],
        [124.2196, 161.9605]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss Function

In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(2153.6538, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()

# Gradients for weights
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[0.4360, 0.1957, 1.0798],
        [0.0348, 1.2928, 0.5063]], requires_grad=True)
tensor([[3192.0906, 2475.4727, 1782.2094],
        [4168.3164, 4522.5474, 2717.4536]])
tensor([-0.2368,  0.0081], requires_grad=True)
tensor([35.8533, 49.1526])


In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 91.1334, 110.9378],
        [125.7669, 149.3458],
        [126.5446, 205.6368],
        [ 92.6019,  77.8821],
        [124.2196, 161.9605]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(2153.6538, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()

# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)

tensor([[ 0.3721,  0.1462,  1.0442],
        [-0.0486,  1.2023,  0.4520]], requires_grad=True)


In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(112.7138, grad_fn=<DivBackward0>)


In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(112.7138, grad_fn=<DivBackward0>)


In [ ]:
# Print predictions
preds

tensor([[ 61.0445,  70.5997],
        [ 88.0201,  96.7015],
        [ 99.2346, 141.5173],
        [ 44.1856,  38.2794],
        [ 98.5031, 111.4970]], grad_fn=<AddBackward0>)