Linear Regression Model using PyTorch built-ins

In [ ]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
from subprocess import call

In [ ]:
# Imports
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [ ]:
import torch

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 87., 134.,  58.],
         [ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [102.,  43.,  37.],
         [ 91.,  88.,  64.]]), tensor([[119., 133.],
         [ 81., 101.],
         [ 22.,  37.],
         [ 22.,  37.],
         [ 81., 101.]])]

In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.0048,  0.5049, -0.4405],
        [ 0.1056,  0.1888, -0.0406]], requires_grad=True)
Parameter containing:
tensor([ 0.0820, -0.4932], requires_grad=True)


Optimizer

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
# Import nn.functional
import torch.nn.functional as F
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4835.8784, grad_fn=<MseLossBackward>)


In [ ]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

In [ ]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(47.2987, grad_fn=<MseLossBackward>)


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.3500,  71.4516],
        [ 77.4888,  97.4632],
        [126.6926, 137.7038],
        [ 27.9872,  44.2971],
        [ 89.7588, 109.2638],
        [ 58.3500,  71.4516],
        [ 77.4888,  97.4632],
        [126.6926, 137.7038],
        [ 27.9872,  44.2971],
        [ 89.7588, 109.2638],
        [ 58.3500,  71.4516],
        [ 77.4888,  97.4632],
        [126.6926, 137.7038],
        [ 27.9872,  44.2971],
        [ 89.7588, 109.2638]], grad_fn=<AddmmBackward>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])